#!/usr/bin/env python3
"""Regression tests for the read-only WizTree outlier finder."""

from __future__ import annotations

import csv
import importlib.util
import subprocess
import sys
import tempfile
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[3]
HELPER_PATH = REPO_ROOT / "scripts" / "windows" / "cleanup" / "find_outliers.py"
spec = importlib.util.spec_from_file_location("find_outliers", HELPER_PATH)
assert spec and spec.loader
module = importlib.util.module_from_spec(spec)
sys.modules[spec.name] = module
spec.loader.exec_module(module)


def assert_true(condition: bool, message: str) -> None:
    if not condition:
        raise AssertionError(f"FAIL: {message}")
    print(f"PASS: {message}")


def add_tree(rows: list[tuple[str, int]], path: str, size_mb: int) -> None:
    rows.append((path, size_mb * module.MIB))


with tempfile.TemporaryDirectory(prefix="cleanup-outlier-test-") as temp:
    fixture = Path(temp) / "wiztree.csv"
    rows: list[tuple[str, int]] = []
    add_tree(rows, "C:\\", 120_000)
    add_tree(rows, "C:\\hiberfil.sys", 6_500)
    add_tree(rows, "C:\\Users", 45_000)
    add_tree(rows, "C:\\Users\\dev", 44_000)
    add_tree(rows, "C:\\Users\\dev\\.cache", 3_000)
    add_tree(rows, "C:\\Users\\dev\\.cache\\puppeteer", 2_700)
    add_tree(rows, "C:\\Users\\dev\\.cache\\puppeteer\\chrome", 1_300)
    add_tree(rows, "C:\\Users\\dev\\.cache\\puppeteer\\headless", 1_200)
    add_tree(rows, "C:\\Users\\dev\\workspace", 5_000)
    add_tree(rows, "C:\\Users\\dev\\workspace\\app", 4_800)
    add_tree(rows, "C:\\Users\\dev\\workspace\\app\\.next", 1_500)
    add_tree(rows, "C:\\Users\\dev\\workspace\\app\\.next\\cache", 1_350)
    add_tree(rows, "C:\\Users\\dev\\workspace\\app\\src", 2_900)
    add_tree(rows, "C:\\Users\\dev\\workspace\\app\\src\\fixture.bin", 2_850)
    add_tree(rows, "C:\\Windows", 35_000)
    add_tree(rows, "C:\\Windows\\WinSxS", 12_000)
    add_tree(rows, "C:\\Windows\\WinSxS\\ManifestCache", 600)
    with fixture.open("w", encoding="utf-8-sig", newline="") as handle:
        handle.write("Generated by WizTree\n")
        writer = csv.writer(handle)
        writer.writerow(["File Name", "Size", "Allocated", "Modified", "Attributes", "Files", "Folders"])
        for path, size in rows:
            writer.writerow([path, size, size, "", "", "", ""])

    entries = module.load_entries(str(fixture))
    hotspots = module.select_hotspots(entries, 100 * module.MIB, 0.80, 9)
    paths = [entry.path.casefold() for entry in hotspots]

    assert_true(not any("hiberfil.sys" in path for path in paths), "hiberfil.sys is never emitted")
    assert_true("c:\\" not in paths, "drive root is not emitted as an outlier")
    assert_true("c:\\users\\dev\\.cache\\puppeteer" in paths, "large cache family is surfaced below the generic cache root")
    assert_true("c:\\users\\dev\\workspace\\app\\.next" in paths, "build-output boundary is surfaced")
    assert_true("c:\\windows\\winsxs\\manifestcache" in paths, "large system descendants remain visible for classification")
    assert_true(all(entry.size >= 100 * module.MIB for entry in hotspots), "every hotspot meets the materiality threshold")
    assert_true(
        all(not (left != right and right.startswith(left.rstrip("\\") + "\\")) for left in paths for right in paths),
        "hotspots do not contain overlapping ancestors and descendants",
    )
    assert_true(
        [entry.size for entry in hotspots] == sorted((entry.size for entry in hotspots), reverse=True),
        "hotspots are sorted largest first",
    )
    result = subprocess.run(
        [sys.executable, str(HELPER_PATH), str(fixture), "--minimum-mb", "100", "--limit", "100"],
        check=True,
        capture_output=True,
        text=True,
    )
    assert_true("hiberfil.sys" not in result.stdout.casefold(), "CLI output cannot surface hiberfil.sys")
    assert_true("|C:\\Users\\dev\\.cache\\puppeteer" in result.stdout, "CLI emits the classified hotspot input format")

print("All cleanup outlier-finder tests passed.")
